from django.contrib import admin

from .models import tblAccountsPayables, tblAccountsReceivables, tblCompanyInformation, tblPettyCash_Details, tblPettyCash_Master, tblUsers, tblCustomer, tblVendor, tblChartOfAccounts, tblCategory, tblEmployee, tblProduct, tblProduct_unit, tblRFQ_Master, tblRFQ_Details, tblSales_Master, tblSales_Details, tblProduct_unit, tblPurchase_Master, tblPurchase_Details, tblSalesOrder_Master, tblSalesOrder_Details,tblPurchaseOrder_Master, tblPurchaseOrder_Details, tblQuotation_Master, tblQuotation_Details, tblPreforma_Master, tblPreforma_Details, tblDeliveryNote_Master, tblDeliveryNote_Details,tblReceipt, tblPayment, tblJournalVoucher_Master, tblJournalVoucher_Details, tblCheques, tblChequeTransfer

admin.site.register(tblUsers)
admin.site.register(tblCategory)
admin.site.register(tblProduct)
admin.site.register(tblProduct_unit)
admin.site.register(tblCustomer)
admin.site.register(tblVendor)
admin.site.register(tblPurchase_Master)
admin.site.register(tblPurchase_Details)
admin.site.register(tblSales_Master)
admin.site.register(tblSales_Details)
admin.site.register(tblAccountsPayables)
admin.site.register(tblAccountsReceivables)
admin.site.register(tblCompanyInformation)
admin.site.register(tblPettyCash_Master)
admin.site.register(tblPettyCash_Details)
admin.site.register(tblChartOfAccounts)
admin.site.register(tblEmployee)
admin.site.register(tblRFQ_Master)
admin.site.register(tblRFQ_Details)
admin.site.register(tblSalesOrder_Master)
admin.site.register(tblSalesOrder_Details)
admin.site.register(tblPurchaseOrder_Master)
admin.site.register(tblPurchaseOrder_Details)
admin.site.register(tblQuotation_Master)
admin.site.register(tblQuotation_Details)
admin.site.register(tblPreforma_Master)
admin.site.register(tblPreforma_Details)
admin.site.register(tblDeliveryNote_Master)
admin.site.register(tblDeliveryNote_Details)
admin.site.register(tblReceipt)
admin.site.register(tblPayment)
admin.site.register(tblJournalVoucher_Master)
admin.site.register(tblJournalVoucher_Details)
admin.site.register(tblCheques)
admin.site.register(tblChequeTransfer)